version: 2
env:
  - GO111MODULE=on

before:
  hooks:
    - go mod tidy
    - go generate ./...

builds:
  - main: ./cmd/desync
    goos:
      - linux
      - darwin
      - windows
    ignore:
      - goos: darwin
        goarch: arm64
      - goos: windows
        goarch: arm64

checksum:
  name_template: 'checksums.txt'

snapshot:
  version_template: "{{ incpatch .Version }}-next"

changelog:
  sort: asc
